config/routes.rb
Rails.application.routes.draw do
  resources :surveys
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :surveys, dependent: :destroy

  validates :status, presence: true


  def total_event
    surveys.sum(:total)
  end

end

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :event

  validates :tasty, :presentation, :atmosphere,
    presence: true,
    numericality: { greater_than: 0, less_than_or_equal_to: 4 }

  
  def total_points()
    self.total = tasty + atmosphere + presentation
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])

  end

  # POST /events or /events.json
  def create
    @event = Event.new(status: event_params[:status],
                        nb_participants: event_params[:nb_participants])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end
  def update_params
    params.permit(:id, :status, :nb_participants)
  end
  # PATCH/PUT /events/1 or /events/1.json
  def update
    @event = Event.find(update_params[:id])
    @event.status = update_params[:status]
    @event.nb_participants = update_params[:nb_participants]

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:status, :nb_participants)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:tasty, :presentation, :atmosphere)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="field">
    <%= form.label :nb_particpants %>
    <%= form.number_field :nb_particpants %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>
  
    <% @events.each do |event| %>
      <% if event.status == 'on going' %>
        <table>
          <thead>
            <tr>
              <th>Event id</th>
              <th>Event status</th>
              <th>Event Total</th>
              <th colspan="4"></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><%= event.id %><td>    
              <td><%= event.status %><td>
              <td><%= event.total_event %><td>
              <td><%= link_to 'Show', event %></td>
              <td><%= link_to 'Edit', edit_event_path(event) %></td>
              <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <td><%= link_to 'Event terminé', event, :class => "btn btn-primary" %></td>
            </tr>
          </tbody>
        </table>
      <% else if event.status == 'pending'%>
        <h3> Event <%= event.id %>, en attente de réalisation !</h3>
      <% else %>
        <h3> Event <%= event.id %> en attente de remplissementage des invités</h3>
      <% end %>
    <% end %>
    <% end %>
<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<h1>Surveys from <%= @event.id %></h1>
<table> 
  <thead>
      <tr>
        <th>Id</th>
        <th>Tasty</th>
        <th>Presentation</th>
        <th>Atmosphere</th>
        <th>Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  </tbody>
    <% @surveys = [] %>
    <% @surveys = @event.surveys %>
    <% @surveys.each do |survey| %>
      <tr>
        <% if survey.event_id == @event.id %> 
          <td><%= survey.id %></td>
          <td><%= survey.tasty %></td>
          <td><%= survey.presentation %></td>
          <td><%= survey.atmosphere %></td>
          <td><%= survey.total %></td>

          <td><%= link_to 'Show', survey %></td>
          <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
          <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>nb of participants : <%= @event.nb_participants %> !</h1>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuveysEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/surveys/_form.html.erb
<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
      <% survey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>The <strong> tasty rate </strong></p>

  <div class="field">
    <% form.label :tasty %>
      <div class="form-check form-check-inline" >
        <input class="form-check-input" type="radio" name="tasty" id="tasty1" value="1">
        <label class="form-check-label" for="tasty1">1</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="tasty" id="tasty2" value="2">
        <label class="form-check-label" for="tasty2">2</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="tasty" id="tasty3" value="3">
        <label class="form-check-label" for="tasty3">3</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="tasty" id="tasty4" value="4">
        <label class="form-check-label" for="tasty4">4</label>
      </div>
    </div>

    <p>The <strong> presentation rate </strong></p>
    <div class="field">
    <% form.label :presentation %>
      <div class="form-check form-check-inline" >
        <input class="form-check-input" type="radio" name="presentation" id="presentation1" value="1">
        <label class="form-check-label" for="presentation1">1</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="presentation" id="presentation2" value="2">
        <label class="form-check-label" for="presentation2">2</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="presentation" id="presentation3" value="3">
        <label class="form-check-label" for="presentation3">3</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="presentation" id="presentation4" value="4">
        <label class="form-check-label" for="presentation4">4</label>
      </div>
    </div>

    <p>The <strong> atmosphere rate </strong></p>
    <div class="field">
    <% form.label :atmosphere %>
      <div class="form-check form-check-inline" >
        <input class="form-check-input" type="radio" name="atmosphere" id="atmosphere1" value="1">
        <label class="form-check-label" for="atmosphere1">1</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="atmosphere" id="atmosphere2" value="2">
        <label class="form-check-label" for="atmosphere2">2</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="atmosphere" id="atmosphere3" value="3">
        <label class="form-check-label" for="atmosphere3">3</label>
      </div>
      <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="atmosphere" id="atmosphere4" value="4">
        <label class="form-check-label" for="atmosphere4">4</label>
      </div>
    </div>
    <input type="submit" value="Submit">

  <div class="field">
    <%= form.label :tasty %>
    <%= form.number_field :tasty %>
  </div>

  <div class="field">
    <%= form.label :presentation %>
    <%= form.number_field :presentation %>
  </div>

  <div class="field">
    <%= form.label :atmosphere %>
    <%= form.number_field :atmosphere %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Tasty</th>
      <th>Presentation</th>
      <th>Atmosphere</th>
      <th>Total</th>
      <th>Event_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @surveys.sort_by { |survey| survey.event_id }.each do |survey| %>
      <tr>
        <td><%= survey.id %></td>
        <td><%= survey.tasty %></td>
        <td><%= survey.presentation %></td>
        <td><%= survey.atmosphere %></td>
        <td><%= survey.total %></td>
        <td><%= survey.event_id %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Surveys from Event <%= (Event.last.id) - 1 %></h1>
<table> 
  <thead>
      <tr>
        <th>Id</th>
        <th>Tasty</th>
        <th>Presentation</th>
        <th>Atmosphere</th>
        <th>Total</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  </tbody>
      <% @surveys.each do |survey| %>
        <tr>
          <% if survey.event_id == (Event.last.id) - 1 %> 
            <td><%= survey.id %></td>
            <td><%= survey.tasty %></td>
            <td><%= survey.presentation %></td>
            <td><%= survey.atmosphere %></td>
            <td><%= survey.total %></td>
            <td><%= link_to 'Show', survey %></td>
            <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
            <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tasty:</strong>
  <%= @survey.tasty %>
</p>

<p>
  <strong>Presentation:</strong>
  <%= @survey.presentation %>
</p>

<p>
  <strong>Atmosphere:</strong>
  <%= @survey.atmosphere %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>